### ISSUE TITLE
NameError: name 't' is not defined

### ISSUE THREAD

**Issue by MandiYang** [techstay/run-python-simply#9]
```
There are aliens invading earth, choose a number below to save earth 
 1) Declare war on the aliens 
 2) Greet the aliens as friends 
t
Traceback (most recent call last):
  File "text_advanture.py", line 5, in <module>
    a=int(input('There are aliens invading earth, choose a number below to save earth \n ' \
  File "<string>", line 1, in <module>
NameError: name 't' is not defined

Process return 1 (0x1)   execution time: 2.365 s
Press Enter to continue...
```

code:
```
import random

while True:
    try:
        a=int(input('There are aliens invading earth, choose a number below to save earth \n ' \
                       '1) Declare war on the aliens \n ' \
                       '2) Greet the aliens as friends \n' \
                       ))
        print(a)
        break
    except ValueError:
        a= input("Input a valid number, not words \n" \
            '1) Declare war on the aliens \n' \
            '2) Greet the aliens as friends \n' )
```

**Comment by MandiYang** [comment]
No, it ran as python2, close issue
